# Generated by Django 4.2 on 2024-07-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_rename_pokemons_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('E', 'Electrico'), ('F', 'Fuego'), ('A', 'Agua'), ('L', 'Lagarto'), ('P', 'Planta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
