# Generated by Django 4.2 on 2024-07-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('P', 'Planta'), ('A', 'Agua'), ('E', 'Eléctrico'), ('F', 'Fuego')], max_length=30),
        ),
    ]
